{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 6,
  "build_id": "v0.106.0",
  "game_mode": "daily",
  "killed_by_encounter": "ENCOUNTER.AEONGLASS_BOSS",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.HAND_OF_GREED"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.HAND_OF_GREED"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.HAND_OF_GREED"
              },
              {
                "id": "CARD.ANOINTED"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.ANOINTED"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.ANOINTED"
              },
              {
                "id": "CARD.FLASH_OF_STEEL"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.FLASH_OF_STEEL"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.FLASH_OF_STEEL"
              },
              {
                "id": "CARD.FISTICUFFS"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.FISTICUFFS"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.FISTICUFFS"
              },
              {
                "id": "CARD.JACKPOT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.JACKPOT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.JACKPOT"
              }
            ],
            "current_gold": 99,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ALL_STAR.title",
                  "table": "modifiers"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "max_hp": 69,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FINISHER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CALCULATED_GAMBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UP_MY_SLEEVE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 112,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.WELL_LAID_PLANS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CALCULATED_GAMBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.WELL_LAID_PLANS"
              },
              {
                "floor_added_to_deck": 3,
                "id": "CARD.WELL_LAID_PLANS"
              },
              {
                "floor_added_to_deck": 3,
                "id": "CARD.WELL_LAID_PLANS"
              }
            ],
            "current_gold": 122,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 67,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 1
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PRECISE_CUT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EXPOSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WELL_LAID_PLANS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PROLONG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REND"
                },
                "was_picked": false
              }
            ],
            "current_gold": 122,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CHANDELIER",
                "was_picked": false
              },
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": false
              },
              {
                "choice": "RELIC.ORRERY",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 122,
            "current_hp": 48,
            "damage_taken": 8,
            "event_choices": [
              {
                "title": {
                  "key": "TRASH_HEAP.pages.INITIAL.options.DIVE_IN.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.HAND_DRILL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TRASH_HEAP",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TACTICIAN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SKEWER"
                },
                "was_picked": false
              }
            ],
            "current_gold": 129,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUDGE_SPINNER_WEAK",
            "monster_ids": [
              "MONSTER.SLUDGE_SPINNER"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 158,
            "current_hp": 28,
            "damage_taken": 20,
            "gold_gained": 29,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLESSING_OF_THE_FORGE",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PLANISPHERE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SKULKING_COLONY_ELITE",
            "monster_ids": [
              "MONSTER.SKULKING_COLONY"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 38,
            "current_hp": 47,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.SPICY_SNAPPY.title",
                  "table": "events"
                },
                "variables": {
                  "CurrentDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Jelly Liver"
                  },
                  "LastDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clam Roll"
                  }
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.CAVIAR.title",
                  "table": "events"
                },
                "variables": {
                  "CurrentDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Jelly Liver"
                  },
                  "LastDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clam Roll"
                  }
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.ALL.options.CLAM_ROLL.title",
                  "table": "events"
                },
                "variables": {
                  "CurrentDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Jelly Liver"
                  },
                  "LastDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clam Roll"
                  }
                }
              },
              {
                "title": {
                  "key": "ENDLESS_CONVEYOR.pages.GRAB_SOMETHING_OFF_THE_BELT.options.LEAVE.title",
                  "table": "events"
                },
                "variables": {
                  "CurrentDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Jelly Liver"
                  },
                  "LastDishTitle": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clam Roll"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 120,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 66,
            "max_hp_gained": 4,
            "max_hp_lost": 1,
            "player_id": 1,
            "upgraded_cards": [
              "CARD.NEUTRALIZE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ENDLESS_CONVEYOR",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STORM_OF_STEEL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              }
            ],
            "current_gold": 64,
            "current_hp": 34,
            "damage_taken": 13,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 101,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 37,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_MARBLES",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.GRAND_FINALE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BUBBLE_BUBBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_DAGGERS"
                },
                "was_picked": false
              }
            ],
            "current_gold": 148,
            "current_hp": 30,
            "damage_taken": 4,
            "gold_gained": 47,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.TUNGSTEN_ROD",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 148,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 148,
            "current_hp": 59,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WATERLOGGED_SCRIPTORIUM.pages.INITIAL.options.BLOODY_INK.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 11,
            "max_hp": 67,
            "max_hp_gained": 6,
            "max_hp_lost": 1,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.WATERLOGGED_SCRIPTORIUM",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POUNCE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 200,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 52,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CULTISTS_NORMAL",
            "monster_ids": [
              "MONSTER.CALCIFIED_CULTIST",
              "MONSTER.DAMP_CULTIST"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 15,
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLADE_DANCE"
              },
              {
                "floor_added_to_deck": 15,
                "id": "CARD.BLADE_DANCE"
              },
              {
                "floor_added_to_deck": 15,
                "id": "CARD.BLADE_DANCE"
              }
            ],
            "current_gold": 231,
            "current_hp": 57,
            "damage_taken": 2,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.JOSS_PAPER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SKULKING_COLONY_ELITE",
            "monster_ids": [
              "MONSTER.SKULKING_COLONY"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 231,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BLADE_DANCE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 17,
                  "id": "CARD.BLADE_OF_INK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SERPENT_FORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULLET_TIME"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLADE_OF_INK"
              },
              {
                "floor_added_to_deck": 17,
                "id": "CARD.BLADE_OF_INK"
              },
              {
                "floor_added_to_deck": 17,
                "id": "CARD.BLADE_OF_INK"
              }
            ],
            "current_gold": 326,
            "current_hp": 37,
            "damage_taken": 20,
            "gold_gained": 95,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_FYSH_BOSS",
            "monster_ids": [
              "MONSTER.SOUL_FYSH"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "GLASS_EYE",
                "title": {
                  "key": "GLASS_EYE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "RADIANT_PEARL",
                "title": {
                  "key": "RADIANT_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "ARCHAIC_TOOTH",
                "title": {
                  "key": "ARCHAIC_TOOTH.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_transformed": [
              {
                "final_card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.SUPPRESS"
                },
                "original_card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 1,
                  "id": "CARD.NEUTRALIZE"
                }
              }
            ],
            "current_gold": 326,
            "current_hp": 57,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ARCHAIC_TOOTH.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.ARCHAIC_TOOTH",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.OROBAS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 341,
            "current_hp": 54,
            "damage_taken": 3,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 61,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_WEAK",
            "monster_ids": [
              "MONSTER.TUNNELER"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": false
              }
            ],
            "current_gold": 369,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 60,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_NECTAR"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SKEWER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TACTICIAN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MALAISE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 404,
            "current_hp": 53,
            "damage_taken": 1,
            "gold_gained": 35,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 59,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.OVICOPTER_NORMAL",
            "monster_ids": [
              "MONSTER.OVICOPTER",
              "MONSTER.TOUGH_EGG"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 446,
            "current_hp": 53,
            "damage_taken": 5,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.PLAIN.title",
                  "table": "events"
                },
                "variables": {
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clumsy"
                  }
                }
              }
            ],
            "gold_gained": 42,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 5,
            "max_hp": 58,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THIS_OR_THAT",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEG_SWEEP"
                },
                "was_picked": false
              }
            ],
            "current_gold": 453,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.BLESSING_OF_THE_FORGE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.HUNTER_KILLER_NORMAL",
            "monster_ids": [
              "MONSTER.HUNTER_KILLER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EXPERTISE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 506,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 53,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 56,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BOTTLED_POTENTIAL",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.STRENGTH_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.LASTING_CANDY",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 506,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 55,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.JACKPOT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 542,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 54,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 542,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 53,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.JACKPOT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.GORGET"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POUNCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOUNCING_FLASK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PHANTOM_BLADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PROLONG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.JACKPOT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 357,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 185,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 52,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GORGET",
                "was_picked": true
              },
              {
                "choice": "RELIC.FESTIVE_POPPER",
                "was_picked": false
              },
              {
                "choice": "RELIC.BURNING_STICKS",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 357,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 51,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.JACKPOT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              }
            ],
            "current_gold": 364,
            "current_hp": 43,
            "damage_taken": 7,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 50,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CHOMPERS_NORMAL",
            "monster_ids": [
              "MONSTER.CHOMPER",
              "MONSTER.CHOMPER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FINISHER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PHANTOM_BLADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BUBBLE_BUBBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MASTER_PLANNER"
                },
                "was_picked": false
              }
            ],
            "current_gold": 393,
            "current_hp": 41,
            "damage_taken": 2,
            "gold_gained": 29,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 49,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.LANTERN",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 393,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 48,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BLADE_OF_INK"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.ADRENALINE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.NIGHTMARE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THE_HUNT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ADRENALINE"
              },
              {
                "floor_added_to_deck": 33,
                "id": "CARD.ADRENALINE"
              },
              {
                "floor_added_to_deck": 33,
                "id": "CARD.ADRENALINE"
              }
            ],
            "current_gold": 468,
            "current_hp": 38,
            "damage_taken": 3,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 47,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_used": [
              "POTION.POWER_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_INSATIABLE_BOSS",
            "monster_ids": [
              "MONSTER.THE_INSATIABLE"
            ],
            "room_type": "boss",
            "turns_taken": 6
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "TRI_BOOMERANG",
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "CLAWS",
                "title": {
                  "key": "CLAWS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "THROWING_AXE",
                "title": {
                  "key": "THROWING_AXE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 18,
                  "id": "CARD.SUPPRESS"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.JACKPOT"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.FLASH_OF_STEEL"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              }
            ],
            "current_gold": 468,
            "current_hp": 45,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "max_hp": 46,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.TRI_BOOMERANG",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TANX",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": false
              }
            ],
            "current_gold": 480,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 45,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
            "monster_ids": [
              "MONSTER.DEVOTED_SCULPTOR"
            ],
            "room_type": "monster",
            "turns_taken": 1
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOOTWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_DAGGERS"
                },
                "was_picked": false
              }
            ],
            "current_gold": 515,
            "current_hp": 44,
            "damage_taken": 0,
            "gold_gained": 35,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 44,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 1
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_colorless": [
              "CARD.MASTER_OF_STRATEGY"
            ],
            "bought_relics": [
              "RELIC.PAPER_KRANE"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFLEX"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WELL_LAID_PLANS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.OMNISLICE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MASTER_OF_STRATEGY"
              },
              {
                "floor_added_to_deck": 37,
                "id": "CARD.MASTER_OF_STRATEGY"
              },
              {
                "floor_added_to_deck": 37,
                "id": "CARD.MASTER_OF_STRATEGY"
              }
            ],
            "current_gold": 111,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 404,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 43,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DUPLICATOR",
                "was_picked": false
              },
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PAPER_KRANE",
                "was_picked": true
              },
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": false
              },
              {
                "choice": "RELIC.MINIATURE_TENT",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              }
            ],
            "current_gold": 123,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 42,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FROG_KNIGHT_NORMAL",
            "monster_ids": [
              "MONSTER.FROG_KNIGHT"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_potions": [
              "POTION.POWER_POTION"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEG_SWEEP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLASH_OF_STEEL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCRAWL"
                },
                "was_picked": false
              }
            ],
            "current_gold": 73,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 50,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 41,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              }
            ],
            "potion_discarded": [
              "POTION.BOTTLED_POTENTIAL"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.POTION_BELT",
                "was_picked": false
              },
              {
                "choice": "RELIC.STURDY_CLAMP",
                "was_picked": false
              },
              {
                "choice": "RELIC.MEMBERSHIP_CARD",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 73,
            "current_hp": 40,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 40,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BLADE_DANCE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 110,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 37,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 39,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.VAMBRACE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 110,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 38,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BLADE_DANCE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.HAZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.REFLEX"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              }
            ],
            "current_gold": 141,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 37,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLESSING_OF_THE_FORGE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.REGAL_PILLOW",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_NEXUS_ELITE",
            "monster_ids": [
              "MONSTER.SOUL_NEXUS"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 141,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 36,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ADRENALINE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 2,
                    "id": "ENCHANTMENT.SHARP"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.FISTICUFFS"
                },
                "enchantment": "ENCHANTMENT.SHARP"
              }
            ],
            "current_gold": 141,
            "current_hp": 35,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SELF_HELP_BOOK.pages.INITIAL.options.READ_THE_BACK.title",
                  "table": "events"
                },
                "variables": {
                  "Enchantment1": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Sharp"
                  },
                  "Enchantment2": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Nimble"
                  },
                  "Enchantment3": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Swift"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 35,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SELF_HELP_BOOK",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.MAD_SCIENCE",
                "props": {
                  "ints": [
                    {
                      "name": "TinkerTimeType",
                      "value": 2
                    },
                    {
                      "name": "TinkerTimeRider",
                      "value": 4
                    }
                  ]
                }
              },
              {
                "floor_added_to_deck": 46,
                "id": "CARD.MAD_SCIENCE",
                "props": {
                  "ints": [
                    {
                      "name": "TinkerTimeType",
                      "value": 2
                    },
                    {
                      "name": "TinkerTimeRider",
                      "value": 4
                    }
                  ]
                }
              },
              {
                "floor_added_to_deck": 46,
                "id": "CARD.MAD_SCIENCE",
                "props": {
                  "ints": [
                    {
                      "name": "TinkerTimeType",
                      "value": 2
                    },
                    {
                      "name": "TinkerTimeRider",
                      "value": 4
                    }
                  ]
                }
              }
            ],
            "current_gold": 141,
            "current_hp": 34,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TINKER_TIME.pages.INITIAL.options.CHOOSE_CARD_TYPE.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_CARD_TYPE.options.SKILL.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "TINKER_TIME.pages.CHOOSE_RIDER.options.ENERGIZED.title",
                  "table": "events"
                },
                "variables": {
                  "ViolenceHits": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  },
                  "CuriousReduction": {
                    "type": "BaseDynamic",
                    "decimal_value": 1,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 34,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TINKER_TIME",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 141,
            "current_hp": 33,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 33,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ADRENALINE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 141,
            "current_hp": 0,
            "damage_taken": 32,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 32,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_used": [
              "POTION.POWER_POTION",
              "POTION.STRENGTH_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.AEONGLASS_BOSS",
            "monster_ids": [
              "MONSTER.AEONGLASS"
            ],
            "room_type": "boss",
            "turns_taken": 5
          }
        ]
      }
    ]
  ],
  "modifiers": [
    {
      "id": "MODIFIER.HOARDER"
    },
    {
      "id": "MODIFIER.ALL_STAR"
    },
    {
      "id": "MODIFIER.TERMINAL"
    }
  ],
  "platform_type": "steam",
  "players": [
    {
      "badges": [
        {
          "id": "CCCCOMBO",
          "rarity": "bronze"
        },
        {
          "id": "ELITE",
          "rarity": "silver"
        }
      ],
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.HAND_OF_GREED"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.HAND_OF_GREED"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.HAND_OF_GREED"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ANOINTED"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ANOINTED"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ANOINTED"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.FLASH_OF_STEEL"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FLASH_OF_STEEL"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FLASH_OF_STEEL"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FISTICUFFS"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FISTICUFFS"
        },
        {
          "enchantment": {
            "amount": 2,
            "id": "ENCHANTMENT.SHARP"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.FISTICUFFS"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.JACKPOT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.JACKPOT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.JACKPOT"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.WELL_LAID_PLANS"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.WELL_LAID_PLANS"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.WELL_LAID_PLANS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 15,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 15,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 15,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "floor_added_to_deck": 17,
          "id": "CARD.BLADE_OF_INK"
        },
        {
          "floor_added_to_deck": 17,
          "id": "CARD.BLADE_OF_INK"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 17,
          "id": "CARD.BLADE_OF_INK"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 18,
          "id": "CARD.SUPPRESS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 33,
          "id": "CARD.ADRENALINE"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.ADRENALINE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 33,
          "id": "CARD.ADRENALINE"
        },
        {
          "floor_added_to_deck": 37,
          "id": "CARD.MASTER_OF_STRATEGY"
        },
        {
          "floor_added_to_deck": 37,
          "id": "CARD.MASTER_OF_STRATEGY"
        },
        {
          "floor_added_to_deck": 37,
          "id": "CARD.MASTER_OF_STRATEGY"
        },
        {
          "floor_added_to_deck": 46,
          "id": "CARD.MAD_SCIENCE",
          "props": {
            "ints": [
              {
                "name": "TinkerTimeType",
                "value": 2
              },
              {
                "name": "TinkerTimeRider",
                "value": 4
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 46,
          "id": "CARD.MAD_SCIENCE",
          "props": {
            "ints": [
              {
                "name": "TinkerTimeType",
                "value": 2
              },
              {
                "name": "TinkerTimeRider",
                "value": 4
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 46,
          "id": "CARD.MAD_SCIENCE",
          "props": {
            "ints": [
              {
                "name": "TinkerTimeType",
                "value": 2
              },
              {
                "name": "TinkerTimeRider",
                "value": 4
              }
            ]
          }
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 5,
          "id": "RELIC.HAND_DRILL"
        },
        {
          "floor_added_to_deck": 7,
          "id": "RELIC.PLANISPHERE"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.BAG_OF_PREPARATION"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.BAG_OF_MARBLES"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.TUNGSTEN_ROD"
        },
        {
          "floor_added_to_deck": 15,
          "id": "RELIC.JOSS_PAPER"
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.ARCHAIC_TOOTH",
          "props": {
            "cards": [
              {
                "name": "AncientCard",
                "value": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SUPPRESS"
                }
              },
              {
                "name": "StarterCard",
                "value": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 1,
                  "id": "CARD.NEUTRALIZE"
                }
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.LASTING_CANDY",
          "props": {
            "ints": [
              {
                "name": "CombatsSeen",
                "value": 7
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.VAJRA"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.GORGET"
        },
        {
          "floor_added_to_deck": 31,
          "id": "RELIC.LANTERN"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.TRI_BOOMERANG"
        },
        {
          "floor_added_to_deck": 37,
          "id": "RELIC.PAPER_KRANE"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.VAMBRACE"
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.REGAL_PILLOW"
        }
      ]
    }
  ],
  "run_time": 33185,
  "schema_version": 9,
  "seed": "22_05_2026_1P",
  "start_time": 1779473520,
  "was_abandoned": false,
  "win": false
}